version: '3'

services:
  app:
    image: "node:14.15.4"
    build: .
    ports:
      - "3333:3333"
    volumes:
      - ".:/home/node/app"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    command: "yarn start:dev"
    